[project]
name = "rag-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astrapy>=1.5.2",
    "deepeval",
    "fastapi[standard]>=0.115.12",
    "google-generativeai>=0.8.4",
    "langchain>=0.3.21",
    "langchain-astradb>=0.5.3",
    "langchain-community>=0.3.20",
    "langchain-groq>=0.3.1",
    "langchain-nvidia-ai-endpoints>=0.3.9",
    "langchain-openai>=0.3.10",
    "openai>=1.68.2",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.0",
]
